#!/bin/bash

# Update package lists
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Set the hostname of the server
HOSTNAME=$(hostname)

# Configure Nginx to add the custom header
sudo tee /etc/nginx/conf.d/custom_http_response_header.conf > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By $HOSTNAME;
    }
}
EOF

# Test Nginx configuration
sudo nginx -t

service nginx restart