#!/usr/bin/env bash
# This Script displays "Best Schoo" 10 times and at 9th time prints "Hi"

counter=1
while [ "$counter" -le 10 ]
do
	echo "Best School"
	if [ "$counter" -eq 9 ]
	then
		echo "Hi"
	fi
	counter=$((counter + 1))
done	
