#!/usr/bin/env bash
# This Script loops from 1 to 10 displays "bad luck" at 4th iteration, "good luck" at 8th iteration, "Best School" for other iterations
counter=1

while [ "$counter" -le 10 ]
do
	if [ "$counter" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$counter" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	counter=$((counter + 1))
done
